package io.github.pouffy.immersive_weathering.datagen.server;

import io.github.pouffy.immersive_weathering.ImmersiveWeathering;
import io.github.pouffy.immersive_weathering.reg.ModBlocks;
import io.github.pouffy.immersive_weathering.reg.ModTags;
import net.mehvahdjukaar.moonlight.api.set.leaves.LeavesTypeRegistry;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends BlockTagsProvider {
    public ModBlockTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, String modId, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, modId, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider pProvider) {
        this.registerModTags();
        this.registerBlockMineables();
        this.registerMinecraftTags();
        this.registerCommonTags();
    }

    protected void registerModTags() {
        tag(ModTags.BARS).add(
                Blocks.IRON_BARS,
                ModBlocks.WAXED_IRON_BARS.get(),
                ModBlocks.EXPOSED_IRON_BARS.get(),
                ModBlocks.WAXED_EXPOSED_IRON_BARS.get(),
                ModBlocks.WEATHERED_IRON_BARS.get(),
                ModBlocks.WAXED_WEATHERED_IRON_BARS.get(),
                ModBlocks.RUSTED_IRON_BARS.get(),
                ModBlocks.WAXED_RUSTED_IRON_BARS.get());
        tag(ModTags.BUBBLES_ASCENDING).add(ModBlocks.MULCH_BLOCK.get());
        tag(ModTags.BUBBLES_DESCENDING).add(ModBlocks.NULCH_BLOCK.get());
        tag(ModTags.CHARRED_BLOCKS).add(
                ModBlocks.CHARRED_LOG.get(),
                ModBlocks.CHARRED_PLANKS.get(),
                ModBlocks.CHARRED_SLAB.get(),
                ModBlocks.CHARRED_STAIRS.get(),
                ModBlocks.CHARRED_FENCE.get(),
                ModBlocks.CHARRED_FENCE_GATE.get());
        tag(ModTags.CLEAN_IRON).add(
                ModBlocks.PLATE_IRON.get(),
                ModBlocks.PLATE_IRON_STAIRS.get(),
                ModBlocks.PLATE_IRON_SLAB.get(),
                ModBlocks.CUT_IRON.get(),
                ModBlocks.CUT_IRON_STAIRS.get(),
                ModBlocks.CUT_IRON_SLAB.get(),
                Blocks.IRON_DOOR,
                Blocks.IRON_TRAPDOOR,
                Blocks.IRON_BARS);
        tag(ModTags.COPPER).add(
                Blocks.EXPOSED_COPPER_BULB,
                Blocks.WEATHERED_COPPER_BULB,
                Blocks.OXIDIZED_COPPER_BULB,
                Blocks.EXPOSED_COPPER_GRATE,
                Blocks.WEATHERED_COPPER_GRATE,
                Blocks.OXIDIZED_COPPER_GRATE,
                Blocks.EXPOSED_COPPER_DOOR,
                Blocks.WEATHERED_COPPER_DOOR,
                Blocks.OXIDIZED_COPPER_DOOR,
                Blocks.EXPOSED_COPPER_TRAPDOOR,
                Blocks.WEATHERED_COPPER_TRAPDOOR,
                Blocks.OXIDIZED_COPPER_TRAPDOOR,
                Blocks.EXPOSED_CHISELED_COPPER,
                Blocks.WEATHERED_CHISELED_COPPER,
                Blocks.OXIDIZED_CHISELED_COPPER,
                Blocks.EXPOSED_COPPER,
                Blocks.WEATHERED_COPPER,
                Blocks.OXIDIZED_COPPER,
                Blocks.EXPOSED_CUT_COPPER,
                Blocks.WEATHERED_CUT_COPPER,
                Blocks.OXIDIZED_CUT_COPPER,
                Blocks.EXPOSED_CUT_COPPER_SLAB,
                Blocks.WEATHERED_CUT_COPPER_SLAB,
                Blocks.OXIDIZED_CUT_COPPER_SLAB,
                Blocks.EXPOSED_CUT_COPPER_STAIRS,
                Blocks.WEATHERED_CUT_COPPER_STAIRS,
                Blocks.OXIDIZED_CUT_COPPER_STAIRS);
        tag(ModTags.CRACK_SOURCE).add(Blocks.LAVA, Blocks.FIRE).addTag(ModTags.CRACKED);
        tag(ModTags.CRACKED).add(
                Blocks.CRACKED_STONE_BRICKS,
                ModBlocks.CRACKED_BRICKS.get(),
                Blocks.CRACKED_NETHER_BRICKS,
                Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS,
                Blocks.CRACKED_DEEPSLATE_BRICKS,
                Blocks.CRACKED_DEEPSLATE_BRICKS,
                ModBlocks.CRACKED_PRISMARINE_BRICKS.get(),
                ModBlocks.CRACKED_END_STONE_BRICKS.get(),
                ModBlocks.CRACKED_STONE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_BRICK_SLAB.get(),
                ModBlocks.CRACKED_NETHER_BRICK_SLAB.get(),
                ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_DEEPSLATE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_DEEPSLATE_TILE_SLAB.get(),
                ModBlocks.CRACKED_PRISMARINE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_END_STONE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_STONE_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_NETHER_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_DEEPSLATE_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_DEEPSLATE_TILE_STAIRS.get(),
                ModBlocks.CRACKED_PRISMARINE_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_END_STONE_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_STONE_BRICK_WALL.get(),
                ModBlocks.CRACKED_BRICK_WALL.get(),
                ModBlocks.CRACKED_NETHER_BRICK_WALL.get(),
                ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_WALL.get(),
                ModBlocks.CRACKED_DEEPSLATE_BRICK_WALL.get(),
                ModBlocks.CRACKED_DEEPSLATE_TILE_WALL.get(),
                ModBlocks.CRACKED_PRISMARINE_BRICK_WALL.get(),
                ModBlocks.CRACKED_END_STONE_BRICK_WALL.get());
        tag(ModTags.DIRT_BASE_BLOCKS).add(
                Blocks.DIRT,
                Blocks.GRASS_BLOCK,
                Blocks.PODZOL,
                ModBlocks.LOAM.get(),
                Blocks.MYCELIUM);
        tag(ModTags.DOUBLE_SANDABLE).add(
                Blocks.COBBLESTONE,
                Blocks.COBBLESTONE_STAIRS,
                Blocks.COBBLESTONE_SLAB,
                Blocks.COBBLESTONE_WALL,
                Blocks.CHISELED_STONE_BRICKS,
                Blocks.STONE_BRICKS,
                Blocks.STONE_BRICK_STAIRS,
                Blocks.STONE_BRICK_SLAB,
                Blocks.STONE_BRICK_WALL);
        tag(ModTags.DOUBLE_SNOWABLE).add(
                Blocks.COBBLESTONE,
                Blocks.COBBLESTONE_STAIRS,
                Blocks.COBBLESTONE_SLAB,
                Blocks.COBBLESTONE_WALL,
                Blocks.CHISELED_STONE_BRICKS,
                Blocks.STONE_BRICKS,
                Blocks.STONE_BRICK_STAIRS,
                Blocks.STONE_BRICK_SLAB,
                Blocks.STONE_BRICK_WALL);
        tag(ModTags.DUNE_GRASS_PATCH_REPLACEABLE).add(
                Blocks.GRASS_BLOCK,
                Blocks.DIRT,
                Blocks.SAND,
                Blocks.COARSE_DIRT);
        tag(ModTags.EXPOSED_IRON).add(
                ModBlocks.EXPOSED_PLATE_IRON.get(),
                ModBlocks.EXPOSED_PLATE_IRON_STAIRS.get(),
                ModBlocks.EXPOSED_PLATE_IRON_SLAB.get(),
                ModBlocks.EXPOSED_CUT_IRON.get(),
                ModBlocks.EXPOSED_CUT_IRON_STAIRS.get(),
                ModBlocks.EXPOSED_CUT_IRON_SLAB.get(),
                ModBlocks.EXPOSED_IRON_DOOR.get(),
                ModBlocks.EXPOSED_IRON_TRAPDOOR.get(),
                ModBlocks.EXPOSED_IRON_BARS.get());
        tag(ModTags.FERTILE_BLOCKS).add(
                Blocks.FARMLAND,
                ModBlocks.SILTY_FARMLAND.get(),
                ModBlocks.EARTHEN_CLAY_FARMLAND.get(),
                ModBlocks.SANDY_FARMLAND.get(),
                ModBlocks.LOAMY_FARMLAND.get());
        tag(ModTags.FIRE_REPLACEABLE).add(ModBlocks.SOOT.get());
        tag(ModTags.GRASS_GROWTH_REPLACEABLE).add(
                ModBlocks.SOOT.get(),
                Blocks.SNOW,
                Blocks.AIR).addTag(ModTags.LEAF_PILES);
        tag(ModTags.GRASS_SPREAD_SOURCE).add(
                ModBlocks.WEEDS.get(),
                Blocks.SHORT_GRASS,
                Blocks.TALL_GRASS,
                Blocks.FERN,
                Blocks.LARGE_FERN);
        tag(ModTags.GRASSY_BLOCKS).add(
                Blocks.GRASS_BLOCK,
                ModBlocks.ROOTED_GRASS_BLOCK.get(),
                ModBlocks.GRASSY_SANDY_DIRT.get(),
                ModBlocks.GRASSY_SILT.get(),
                ModBlocks.GRASSY_EARTHEN_CLAY.get(),
                ModBlocks.GRASSY_PERMAFROST.get());
        tag(ModTags.ICE).add(
                Blocks.ICE,
                Blocks.PACKED_ICE,
                Blocks.BLUE_ICE);
        tag(ModTags.ICICLE_REPLACEABLE_BLOCKS).add(
                Blocks.ICE,
                Blocks.PACKED_ICE,
                Blocks.BLUE_ICE).addTag(BlockTags.BASE_STONE_OVERWORLD);
        tag(ModTags.LEAF_PILE_REPLACEABLE).add(
                ModBlocks.SOOT.get(),
                ModBlocks.IVY.get(),
                Blocks.AIR).addTag(ModTags.SMALL_PLANTS);
        tag(ModTags.LEAF_PILES).add(
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("oak"))),
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("birch"))),
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("spruce"))),
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("jungle"))),
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("acacia"))),
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("dark_oak"))),
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("mangrove"))),
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("cherry"))),
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("azalea"))),
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("flowering_azalea"))));
        tag(ModTags.LEAFY_LEAVES).add(
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("oak"))),
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("birch"))),
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("jungle"))),
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("dark_oak"))),
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("mangrove"))));
        tag(ModTags.PINE_LEAVES).add(ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("spruce"))));
        tag(ModTags.MAGMA_SOURCE).add(Blocks.LAVA, Blocks.MAGMA_BLOCK);
        tag(ModTags.MOSS_SOURCE).add(Blocks.MOSS_BLOCK, Blocks.MOSS_CARPET, Blocks.VINE, Blocks.WATER);
        tag(ModTags.MOSSY).add(
                Blocks.MOSSY_COBBLESTONE,
                Blocks.MOSSY_COBBLESTONE_STAIRS,
                Blocks.MOSSY_COBBLESTONE_SLAB,
                Blocks.MOSSY_COBBLESTONE_WALL,
                Blocks.MOSSY_STONE_BRICKS,
                ModBlocks.MOSSY_CHISELED_STONE_BRICKS.get(),
                Blocks.MOSSY_STONE_BRICK_SLAB,
                Blocks.MOSSY_STONE_BRICK_STAIRS,
                Blocks.MOSSY_STONE_BRICK_WALL,
                ModBlocks.MOSSY_BRICKS.get(),
                ModBlocks.MOSSY_BRICK_STAIRS.get(),
                ModBlocks.MOSSY_BRICK_SLAB.get(),
                ModBlocks.MOSSY_BRICK_WALL.get(),
                ModBlocks.MOSSY_STONE.get(),
                ModBlocks.MOSSY_STONE_STAIRS.get(),
                ModBlocks.MOSSY_STONE_SLAB.get(),
                ModBlocks.MOSSY_STONE_WALL.get());
        tag(ModTags.QUARTZ_BLOCKS).add(Blocks.QUARTZ_BLOCK, Blocks.SMOOTH_QUARTZ).addOptional(ImmersiveWeathering.res("spelunkery:rough_quartz_block"));
        tag(ModTags.RUSTED_IRON).add(
                ModBlocks.RUSTED_PLATE_IRON.get(),
                ModBlocks.RUSTED_PLATE_IRON_STAIRS.get(),
                ModBlocks.RUSTED_PLATE_IRON_SLAB.get(),
                ModBlocks.RUSTED_CUT_IRON.get(),
                ModBlocks.RUSTED_CUT_IRON_STAIRS.get(),
                ModBlocks.RUSTED_CUT_IRON_SLAB.get(),
                ModBlocks.RUSTED_IRON_DOOR.get(),
                ModBlocks.RUSTED_IRON_TRAPDOOR.get(),
                ModBlocks.RUSTED_IRON_BARS.get());
        tag(ModTags.SANDY).add(
                ModBlocks.SANDY_COBBLESTONE.get(),
                ModBlocks.SANDY_COBBLESTONE_STAIRS.get(),
                ModBlocks.SANDY_COBBLESTONE_SLAB.get(),
                ModBlocks.SANDY_COBBLESTONE_WALL.get(),
                ModBlocks.SANDY_STONE_BRICKS.get(),
                ModBlocks.SANDY_CHISELED_STONE_BRICKS.get(),
                ModBlocks.SANDY_STONE_BRICK_SLAB.get(),
                ModBlocks.SANDY_STONE_BRICK_STAIRS.get(),
                ModBlocks.SANDY_STONE_BRICK_WALL.get(),
                ModBlocks.SANDY_STONE.get(),
                ModBlocks.SANDY_STONE_STAIRS.get(),
                ModBlocks.SANDY_STONE_SLAB.get(),
                ModBlocks.SANDY_STONE_WALL.get());
        tag(ModTags.SMALL_MUSHROOMS).add(Blocks.RED_MUSHROOM, Blocks.BROWN_MUSHROOM);
        tag(ModTags.SMALL_PLANTS).add(
                ModBlocks.FROSTY_GRASS.get(),
                ModBlocks.FROSTY_FERN.get(),
                Blocks.SHORT_GRASS,
                Blocks.FERN).addTag(ModTags.LEAF_PILES).addTag(BlockTags.FLOWERS);
        tag(ModTags.SMOKEY_BLOCKS).add(Blocks.HAY_BLOCK, ModBlocks.MULCH_BLOCK.get());
        tag(ModTags.SNOWY).add(
                ModBlocks.SNOWY_COBBLESTONE.get(),
                ModBlocks.SNOWY_COBBLESTONE_STAIRS.get(),
                ModBlocks.SNOWY_COBBLESTONE_SLAB.get(),
                ModBlocks.SNOWY_COBBLESTONE_WALL.get(),
                ModBlocks.SNOWY_STONE_BRICKS.get(),
                ModBlocks.SNOWY_CHISELED_STONE_BRICKS.get(),
                ModBlocks.SNOWY_STONE_BRICK_SLAB.get(),
                ModBlocks.SNOWY_STONE_BRICK_STAIRS.get(),
                ModBlocks.SNOWY_STONE_BRICK_WALL.get(),
                ModBlocks.SNOWY_STONE.get(),
                ModBlocks.SNOWY_STONE_STAIRS.get(),
                ModBlocks.SNOWY_STONE_SLAB.get(),
                ModBlocks.SNOWY_STONE_WALL.get());
        tag(ModTags.CLAY_SOIL_CROP).add(Blocks.WHEAT, Blocks.BAMBOO_SAPLING, Blocks.BAMBOO);
        tag(ModTags.LOAM_SOIL_CROP).add(Blocks.MELON_STEM, Blocks.PUMPKIN_STEM, Blocks.SWEET_BERRY_BUSH)
                .addOptional(ImmersiveWeathering.res("farmers_delight:budding_tomatoes"))
                .addOptional(ImmersiveWeathering.res("farmers_delight:tomatoes"));
        tag(ModTags.SAND_SOIL_CROP).add(Blocks.CARROTS, Blocks.BEETROOTS).addOptional(ImmersiveWeathering.res("farmers_delight:cabbages"));
        tag(ModTags.SILT_SOIL_CROP).add(Blocks.POTATOES, Blocks.WHEAT)
                .addOptional(ImmersiveWeathering.res("farmers_delight:cabbages"))
                .addOptional(ImmersiveWeathering.res("farmers_delight:onions"))
                .addOptional(ImmersiveWeathering.res("supplementaries:flax"));
        tag(ModTags.UNSCRAPEABLE).addTag(ModTags.RUSTED_IRON);
        tag(ModTags.WAXED_BLOCKS).add(
                Blocks.WAXED_COPPER_BULB,
                Blocks.WAXED_EXPOSED_COPPER_BULB,
                Blocks.WAXED_WEATHERED_COPPER_BULB,
                Blocks.WAXED_OXIDIZED_COPPER_BULB,
                Blocks.WAXED_COPPER_GRATE,
                Blocks.WAXED_EXPOSED_COPPER_GRATE,
                Blocks.WAXED_WEATHERED_COPPER_GRATE,
                Blocks.WAXED_OXIDIZED_COPPER_GRATE,
                Blocks.WAXED_COPPER_DOOR,
                Blocks.WAXED_EXPOSED_COPPER_DOOR,
                Blocks.WAXED_WEATHERED_COPPER_DOOR,
                Blocks.WAXED_OXIDIZED_COPPER_DOOR,
                Blocks.WAXED_COPPER_TRAPDOOR,
                Blocks.WAXED_EXPOSED_COPPER_TRAPDOOR,
                Blocks.WAXED_WEATHERED_COPPER_TRAPDOOR,
                Blocks.WAXED_OXIDIZED_COPPER_TRAPDOOR,
                Blocks.WAXED_CHISELED_COPPER,
                Blocks.WAXED_EXPOSED_CHISELED_COPPER,
                Blocks.WAXED_WEATHERED_CHISELED_COPPER,
                Blocks.WAXED_OXIDIZED_CHISELED_COPPER,
                Blocks.WAXED_COPPER_BLOCK,
                Blocks.WAXED_EXPOSED_COPPER,
                Blocks.WAXED_WEATHERED_COPPER,
                Blocks.WAXED_OXIDIZED_COPPER,
                Blocks.WAXED_CUT_COPPER,
                Blocks.WAXED_EXPOSED_CUT_COPPER,
                Blocks.WAXED_WEATHERED_CUT_COPPER,
                Blocks.WAXED_OXIDIZED_CUT_COPPER,
                Blocks.WAXED_CUT_COPPER_SLAB,
                Blocks.WAXED_EXPOSED_CUT_COPPER_SLAB,
                Blocks.WAXED_WEATHERED_CUT_COPPER_SLAB,
                Blocks.WAXED_OXIDIZED_CUT_COPPER_SLAB,
                Blocks.WAXED_CUT_COPPER_STAIRS,
                Blocks.WAXED_EXPOSED_CUT_COPPER_STAIRS,
                Blocks.WAXED_WEATHERED_CUT_COPPER_STAIRS,
                Blocks.WAXED_OXIDIZED_CUT_COPPER_STAIRS,
                ModBlocks.WAXED_PLATE_IRON.get(),
                ModBlocks.WAXED_EXPOSED_PLATE_IRON.get(),
                ModBlocks.WAXED_WEATHERED_PLATE_IRON.get(),
                ModBlocks.WAXED_RUSTED_PLATE_IRON.get(),
                ModBlocks.WAXED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_EXPOSED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_WEATHERED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_RUSTED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_EXPOSED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_WEATHERED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_RUSTED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_CUT_IRON.get(),
                ModBlocks.WAXED_EXPOSED_CUT_IRON.get(),
                ModBlocks.WAXED_WEATHERED_CUT_IRON.get(),
                ModBlocks.WAXED_RUSTED_CUT_IRON.get(),
                ModBlocks.WAXED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_EXPOSED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_WEATHERED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_RUSTED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_EXPOSED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_WEATHERED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_RUSTED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_IRON_DOOR.get(),
                ModBlocks.WAXED_EXPOSED_IRON_DOOR.get(),
                ModBlocks.WAXED_WEATHERED_IRON_DOOR.get(),
                ModBlocks.WAXED_RUSTED_IRON_DOOR.get(),
                ModBlocks.WAXED_IRON_TRAPDOOR.get(),
                ModBlocks.WAXED_EXPOSED_IRON_TRAPDOOR.get(),
                ModBlocks.WAXED_WEATHERED_IRON_TRAPDOOR.get(),
                ModBlocks.WAXED_RUSTED_IRON_TRAPDOOR.get(),
                ModBlocks.WAXED_IRON_BARS.get(),
                ModBlocks.WAXED_EXPOSED_IRON_BARS.get(),
                ModBlocks.WAXED_WEATHERED_IRON_BARS.get(),
                ModBlocks.WAXED_RUSTED_IRON_BARS.get());
        tag(ModTags.WEATHERED_IRON).add(
                ModBlocks.WEATHERED_PLATE_IRON.get(),
                ModBlocks.WEATHERED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WEATHERED_PLATE_IRON_SLAB.get(),
                ModBlocks.WEATHERED_CUT_IRON.get(),
                ModBlocks.WEATHERED_CUT_IRON_STAIRS.get(),
                ModBlocks.WEATHERED_CUT_IRON_SLAB.get(),
                ModBlocks.WEATHERED_IRON_DOOR.get(),
                ModBlocks.WEATHERED_IRON_TRAPDOOR.get(),
                ModBlocks.WEATHERED_IRON_BARS.get());
        tag(ModTags.WEED_REPLACEABLE).add(Blocks.AIR).addTag(BlockTags.CROPS);
        tag(ModTags.SILT_REPLACEABLE).add(Blocks.DIRT, Blocks.CLAY, Blocks.SAND, Blocks.GRAVEL);
        tag(ModTags.PERMAFROST_REPLACEABLE).add(Blocks.DIRT, Blocks.STONE, Blocks.SNOW_BLOCK);
    }

    protected void registerBlockMineables() {
        tag(BlockTags.NEEDS_STONE_TOOL).add(
                ModBlocks.ICICLE.get(),
                ModBlocks.PLATE_IRON.get(),
                ModBlocks.EXPOSED_PLATE_IRON.get(),
                ModBlocks.WEATHERED_PLATE_IRON.get(),
                ModBlocks.RUSTED_PLATE_IRON.get(),
                ModBlocks.PLATE_IRON_STAIRS.get(),
                ModBlocks.EXPOSED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WEATHERED_PLATE_IRON_STAIRS.get(),
                ModBlocks.RUSTED_PLATE_IRON_STAIRS.get(),
                ModBlocks.PLATE_IRON_SLAB.get(),
                ModBlocks.EXPOSED_PLATE_IRON_SLAB.get(),
                ModBlocks.WEATHERED_PLATE_IRON_SLAB.get(),
                ModBlocks.RUSTED_PLATE_IRON_SLAB.get(),
                ModBlocks.CUT_IRON.get(),
                ModBlocks.EXPOSED_CUT_IRON.get(),
                ModBlocks.WEATHERED_CUT_IRON.get(),
                ModBlocks.RUSTED_CUT_IRON.get(),
                ModBlocks.CUT_IRON_STAIRS.get(),
                ModBlocks.EXPOSED_CUT_IRON_STAIRS.get(),
                ModBlocks.WEATHERED_CUT_IRON_STAIRS.get(),
                ModBlocks.RUSTED_CUT_IRON_STAIRS.get(),
                ModBlocks.CUT_IRON_SLAB.get(),
                ModBlocks.EXPOSED_CUT_IRON_SLAB.get(),
                ModBlocks.WEATHERED_CUT_IRON_SLAB.get(),
                ModBlocks.RUSTED_CUT_IRON_SLAB.get(),
                ModBlocks.EXPOSED_IRON_DOOR.get(),
                ModBlocks.WEATHERED_IRON_DOOR.get(),
                ModBlocks.RUSTED_IRON_DOOR.get(),
                ModBlocks.EXPOSED_IRON_TRAPDOOR.get(),
                ModBlocks.WEATHERED_IRON_TRAPDOOR.get(),
                ModBlocks.RUSTED_IRON_TRAPDOOR.get(),
                ModBlocks.EXPOSED_IRON_BARS.get(),
                ModBlocks.WEATHERED_IRON_BARS.get(),
                ModBlocks.RUSTED_IRON_BARS.get(),
                ModBlocks.WAXED_PLATE_IRON.get(),
                ModBlocks.WAXED_EXPOSED_PLATE_IRON.get(),
                ModBlocks.WAXED_WEATHERED_PLATE_IRON.get(),
                ModBlocks.WAXED_RUSTED_PLATE_IRON.get(),
                ModBlocks.WAXED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_EXPOSED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_WEATHERED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_RUSTED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_EXPOSED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_WEATHERED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_RUSTED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_CUT_IRON.get(),
                ModBlocks.WAXED_EXPOSED_CUT_IRON.get(),
                ModBlocks.WAXED_WEATHERED_CUT_IRON.get(),
                ModBlocks.WAXED_RUSTED_CUT_IRON.get(),
                ModBlocks.WAXED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_EXPOSED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_WEATHERED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_RUSTED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_EXPOSED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_WEATHERED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_RUSTED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_IRON_DOOR.get(),
                ModBlocks.WAXED_EXPOSED_IRON_DOOR.get(),
                ModBlocks.WAXED_WEATHERED_IRON_DOOR.get(),
                ModBlocks.WAXED_RUSTED_IRON_DOOR.get(),
                ModBlocks.WAXED_IRON_TRAPDOOR.get(),
                ModBlocks.WAXED_EXPOSED_IRON_TRAPDOOR.get(),
                ModBlocks.WAXED_WEATHERED_IRON_TRAPDOOR.get(),
                ModBlocks.WAXED_RUSTED_IRON_TRAPDOOR.get(),
                ModBlocks.WAXED_IRON_BARS.get(),
                ModBlocks.WAXED_EXPOSED_IRON_BARS.get(),
                ModBlocks.WAXED_WEATHERED_IRON_BARS.get(),
                ModBlocks.WAXED_RUSTED_IRON_BARS.get());
        tag(BlockTags.MINEABLE_WITH_AXE).add(
                ModBlocks.CHARRED_LOG.get(),
                ModBlocks.CHARRED_PLANKS.get(),
                ModBlocks.CHARRED_SLAB.get(),
                ModBlocks.CHARRED_STAIRS.get(),
                ModBlocks.CHARRED_FENCE.get(),
                ModBlocks.CHARRED_FENCE_GATE.get());
        tag(BlockTags.MINEABLE_WITH_PICKAXE).add(
                ModBlocks.VITRIFIED_SAND.get(),
                ModBlocks.FULGURITE.get(),
                ModBlocks.ICICLE.get(),
                ModBlocks.EARTHEN_CLAY.get(),
                ModBlocks.PERMAFROST.get(),
                ModBlocks.GRASSY_EARTHEN_CLAY.get(),
                ModBlocks.GRASSY_PERMAFROST.get(),
                ModBlocks.EARTHEN_CLAY_FARMLAND.get(),
                ModBlocks.MOSSY_STONE.get(),
                ModBlocks.MOSSY_STONE_STAIRS.get(),
                ModBlocks.MOSSY_STONE_SLAB.get(),
                ModBlocks.MOSSY_STONE_WALL.get(),
                ModBlocks.STONE_WALL.get(),
                ModBlocks.MOSSY_BRICKS.get(),
                ModBlocks.MOSSY_CHISELED_STONE_BRICKS.get(),
                ModBlocks.MOSSY_BRICK_STAIRS.get(),
                ModBlocks.MOSSY_BRICK_SLAB.get(),
                ModBlocks.MOSSY_BRICK_WALL.get(),
                ModBlocks.PRISMARINE_BRICK_WALL.get(),
                ModBlocks.DARK_PRISMARINE_WALL.get(),
                ModBlocks.CHISELED_PRISMARINE_BRICKS.get(),
                ModBlocks.CRACKED_BRICKS.get(),
                ModBlocks.CRACKED_PRISMARINE_BRICKS.get(),
                ModBlocks.CRACKED_END_STONE_BRICKS.get(),
                ModBlocks.CRACKED_BRICK_WALL.get(),
                ModBlocks.CRACKED_STONE_BRICK_WALL.get(),
                ModBlocks.CRACKED_NETHER_BRICK_WALL.get(),
                ModBlocks.CRACKED_DEEPSLATE_BRICK_WALL.get(),
                ModBlocks.CRACKED_DEEPSLATE_TILE_WALL.get(),
                ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_WALL.get(),
                ModBlocks.CRACKED_PRISMARINE_BRICK_WALL.get(),
                ModBlocks.CRACKED_END_STONE_BRICK_WALL.get(),
                ModBlocks.CRACKED_BRICK_SLAB.get(),
                ModBlocks.CRACKED_STONE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_NETHER_BRICK_SLAB.get(),
                ModBlocks.CRACKED_DEEPSLATE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_DEEPSLATE_TILE_SLAB.get(),
                ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_PRISMARINE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_END_STONE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_STONE_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_NETHER_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_DEEPSLATE_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_DEEPSLATE_TILE_STAIRS.get(),
                ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_PRISMARINE_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_END_STONE_BRICK_STAIRS.get(),
                ModBlocks.PLATE_IRON.get(),
                ModBlocks.EXPOSED_PLATE_IRON.get(),
                ModBlocks.WEATHERED_PLATE_IRON.get(),
                ModBlocks.RUSTED_PLATE_IRON.get(),
                ModBlocks.PLATE_IRON_STAIRS.get(),
                ModBlocks.EXPOSED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WEATHERED_PLATE_IRON_STAIRS.get(),
                ModBlocks.RUSTED_PLATE_IRON_STAIRS.get(),
                ModBlocks.PLATE_IRON_SLAB.get(),
                ModBlocks.EXPOSED_PLATE_IRON_SLAB.get(),
                ModBlocks.WEATHERED_PLATE_IRON_SLAB.get(),
                ModBlocks.RUSTED_PLATE_IRON_SLAB.get(),
                ModBlocks.CUT_IRON.get(),
                ModBlocks.EXPOSED_CUT_IRON.get(),
                ModBlocks.WEATHERED_CUT_IRON.get(),
                ModBlocks.RUSTED_CUT_IRON.get(),
                ModBlocks.CUT_IRON_STAIRS.get(),
                ModBlocks.EXPOSED_CUT_IRON_STAIRS.get(),
                ModBlocks.WEATHERED_CUT_IRON_STAIRS.get(),
                ModBlocks.RUSTED_CUT_IRON_STAIRS.get(),
                ModBlocks.CUT_IRON_SLAB.get(),
                ModBlocks.EXPOSED_CUT_IRON_SLAB.get(),
                ModBlocks.WEATHERED_CUT_IRON_SLAB.get(),
                ModBlocks.RUSTED_CUT_IRON_SLAB.get(),
                ModBlocks.EXPOSED_IRON_DOOR.get(),
                ModBlocks.WEATHERED_IRON_DOOR.get(),
                ModBlocks.RUSTED_IRON_DOOR.get(),
                ModBlocks.EXPOSED_IRON_TRAPDOOR.get(),
                ModBlocks.WEATHERED_IRON_TRAPDOOR.get(),
                ModBlocks.RUSTED_IRON_TRAPDOOR.get(),
                ModBlocks.EXPOSED_IRON_BARS.get(),
                ModBlocks.WEATHERED_IRON_BARS.get(),
                ModBlocks.RUSTED_IRON_BARS.get(),
                ModBlocks.WAXED_PLATE_IRON.get(),
                ModBlocks.WAXED_EXPOSED_PLATE_IRON.get(),
                ModBlocks.WAXED_WEATHERED_PLATE_IRON.get(),
                ModBlocks.WAXED_RUSTED_PLATE_IRON.get(),
                ModBlocks.WAXED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_EXPOSED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_WEATHERED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_RUSTED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_EXPOSED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_WEATHERED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_RUSTED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_CUT_IRON.get(),
                ModBlocks.WAXED_EXPOSED_CUT_IRON.get(),
                ModBlocks.WAXED_WEATHERED_CUT_IRON.get(),
                ModBlocks.WAXED_RUSTED_CUT_IRON.get(),
                ModBlocks.WAXED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_EXPOSED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_WEATHERED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_RUSTED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_EXPOSED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_WEATHERED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_RUSTED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_IRON_DOOR.get(),
                ModBlocks.WAXED_EXPOSED_IRON_DOOR.get(),
                ModBlocks.WAXED_WEATHERED_IRON_DOOR.get(),
                ModBlocks.WAXED_RUSTED_IRON_DOOR.get(),
                ModBlocks.WAXED_IRON_TRAPDOOR.get(),
                ModBlocks.WAXED_EXPOSED_IRON_TRAPDOOR.get(),
                ModBlocks.WAXED_WEATHERED_IRON_TRAPDOOR.get(),
                ModBlocks.WAXED_RUSTED_IRON_TRAPDOOR.get(),
                ModBlocks.WAXED_IRON_BARS.get(),
                ModBlocks.WAXED_EXPOSED_IRON_BARS.get(),
                ModBlocks.WAXED_WEATHERED_IRON_BARS.get(),
                ModBlocks.WAXED_RUSTED_IRON_BARS.get(),
                ModBlocks.SNOWY_STONE.get(),
                ModBlocks.SNOWY_STONE_STAIRS.get(),
                ModBlocks.SNOWY_STONE_SLAB.get(),
                ModBlocks.SNOWY_STONE_WALL.get(),
                ModBlocks.SNOWY_COBBLESTONE.get(),
                ModBlocks.SNOWY_COBBLESTONE_STAIRS.get(),
                ModBlocks.SNOWY_COBBLESTONE_SLAB.get(),
                ModBlocks.SNOWY_COBBLESTONE_WALL.get(),
                ModBlocks.SNOWY_STONE_BRICKS.get(),
                ModBlocks.SNOWY_CHISELED_STONE_BRICKS.get(),
                ModBlocks.SNOWY_STONE_BRICK_STAIRS.get(),
                ModBlocks.SNOWY_STONE_BRICK_SLAB.get(),
                ModBlocks.SNOWY_STONE_BRICK_WALL.get(),
                ModBlocks.SANDY_STONE.get(),
                ModBlocks.SANDY_STONE_STAIRS.get(),
                ModBlocks.SANDY_STONE_SLAB.get(),
                ModBlocks.SANDY_STONE_WALL.get(),
                ModBlocks.SANDY_COBBLESTONE.get(),
                ModBlocks.SANDY_COBBLESTONE_STAIRS.get(),
                ModBlocks.SANDY_COBBLESTONE_SLAB.get(),
                ModBlocks.SANDY_COBBLESTONE_WALL.get(),
                ModBlocks.SANDY_STONE_BRICKS.get(),
                ModBlocks.SANDY_CHISELED_STONE_BRICKS.get(),
                ModBlocks.SANDY_STONE_BRICK_STAIRS.get(),
                ModBlocks.SANDY_STONE_BRICK_SLAB.get(),
                ModBlocks.SANDY_STONE_BRICK_WALL.get());
        tag(BlockTags.MINEABLE_WITH_SHOVEL).add(
                ModBlocks.MULCH_BLOCK.get(),
                ModBlocks.NULCH_BLOCK.get(),
                ModBlocks.ROOTED_GRASS_BLOCK.get(),
                ModBlocks.SAND_LAYER_BLOCK.get(),
                ModBlocks.RED_SAND_LAYER_BLOCK.get(),
                ModBlocks.EARTHEN_CLAY.get(),
                ModBlocks.PERMAFROST.get(),
                ModBlocks.SILT.get(),
                ModBlocks.LOAM.get(),
                ModBlocks.SANDY_DIRT.get(),
                ModBlocks.GRASSY_EARTHEN_CLAY.get(),
                ModBlocks.GRASSY_PERMAFROST.get(),
                ModBlocks.GRASSY_SILT.get(),
                ModBlocks.GRASSY_SANDY_DIRT.get(),
                ModBlocks.EARTHEN_CLAY_FARMLAND.get(),
                ModBlocks.SILTY_FARMLAND.get(),
                ModBlocks.LOAMY_FARMLAND.get(),
                ModBlocks.SANDY_FARMLAND.get());
    }

    protected void registerMinecraftTags() {
        tag(BlockTags.ANIMALS_SPAWNABLE_ON).addTag(BlockTags.DIRT);
        tag(BlockTags.BAMBOO_PLANTABLE_ON).add(
                ModBlocks.SILTY_FARMLAND.get(),
                ModBlocks.EARTHEN_CLAY_FARMLAND.get(),
                ModBlocks.SANDY_FARMLAND.get(),
                ModBlocks.LOAMY_FARMLAND.get());
        tag(BlockTags.CLIMBABLE).add(
                Blocks.HANGING_ROOTS,
                ModBlocks.HANGING_ROOTS_WALL.get(),
                ModBlocks.IVY.get());
        tag(BlockTags.DIRT).add(
                ModBlocks.MULCH_BLOCK.get(),
                ModBlocks.ROOTED_GRASS_BLOCK.get(),
                ModBlocks.LOAM.get(),
                ModBlocks.SILT.get(),
                ModBlocks.EARTHEN_CLAY.get(),
                ModBlocks.SANDY_DIRT.get(),
                ModBlocks.PERMAFROST.get(),
                ModBlocks.GRASSY_SILT.get(),
                ModBlocks.GRASSY_EARTHEN_CLAY.get(),
                ModBlocks.GRASSY_SANDY_DIRT.get(),
                ModBlocks.GRASSY_PERMAFROST.get());
        tag(BlockTags.FENCE_GATES).add(ModBlocks.CHARRED_FENCE_GATE.get());
        tag(BlockTags.FOXES_SPAWNABLE_ON).addTag(BlockTags.DIRT);
        tag(BlockTags.GOATS_SPAWNABLE_ON).addTag(BlockTags.DIRT);
        tag(BlockTags.MOSS_REPLACEABLE).addTag(ModTags.MOSSY);
        tag(BlockTags.MUSHROOM_GROW_BLOCK).add(
                ModBlocks.MULCH_BLOCK.get(),
                ModBlocks.NULCH_BLOCK.get());
        tag(BlockTags.RABBITS_SPAWNABLE_ON).addTag(BlockTags.DIRT);
        tag(BlockTags.SLABS).add(
                ModBlocks.MOSSY_STONE_SLAB.get(),
                ModBlocks.MOSSY_BRICK_SLAB.get(),
                ModBlocks.CRACKED_BRICK_SLAB.get(),
                ModBlocks.CRACKED_STONE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_NETHER_BRICK_SLAB.get(),
                ModBlocks.CRACKED_DEEPSLATE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_DEEPSLATE_TILE_SLAB.get(),
                ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_PRISMARINE_BRICK_SLAB.get(),
                ModBlocks.CRACKED_END_STONE_BRICK_SLAB.get(),
                ModBlocks.PLATE_IRON_SLAB.get(),
                ModBlocks.EXPOSED_PLATE_IRON_SLAB.get(),
                ModBlocks.WEATHERED_PLATE_IRON_SLAB.get(),
                ModBlocks.RUSTED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_EXPOSED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_WEATHERED_PLATE_IRON_SLAB.get(),
                ModBlocks.WAXED_RUSTED_PLATE_IRON_SLAB.get(),
                ModBlocks.CUT_IRON_SLAB.get(),
                ModBlocks.EXPOSED_CUT_IRON_SLAB.get(),
                ModBlocks.WEATHERED_CUT_IRON_SLAB.get(),
                ModBlocks.RUSTED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_EXPOSED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_WEATHERED_CUT_IRON_SLAB.get(),
                ModBlocks.WAXED_RUSTED_CUT_IRON_SLAB.get(),
                ModBlocks.SNOWY_STONE_SLAB.get(),
                ModBlocks.SNOWY_COBBLESTONE_SLAB.get(),
                ModBlocks.SNOWY_STONE_BRICK_SLAB.get(),
                ModBlocks.SANDY_STONE_SLAB.get(),
                ModBlocks.SANDY_COBBLESTONE_SLAB.get(),
                ModBlocks.SANDY_STONE_BRICK_SLAB.get(),
                ModBlocks.CHARRED_SLAB.get());
        tag(BlockTags.SMALL_FLOWERS).add(
                ModBlocks.LEAF_PILES.get(LeavesTypeRegistry.INSTANCE.get(ResourceLocation.withDefaultNamespace("flowering_azalea"))),
                ModBlocks.AZALEA_FLOWER_PILE.get());
        tag(BlockTags.SOUL_FIRE_BASE_BLOCKS).add(Blocks.CRYING_OBSIDIAN);
        tag(BlockTags.STAIRS).add(
                ModBlocks.MOSSY_STONE_STAIRS.get(),
                ModBlocks.MOSSY_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_STONE_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_NETHER_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_DEEPSLATE_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_DEEPSLATE_TILE_STAIRS.get(),
                ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_PRISMARINE_BRICK_STAIRS.get(),
                ModBlocks.CRACKED_END_STONE_BRICK_STAIRS.get(),
                ModBlocks.PLATE_IRON_STAIRS.get(),
                ModBlocks.EXPOSED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WEATHERED_PLATE_IRON_STAIRS.get(),
                ModBlocks.RUSTED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_EXPOSED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_WEATHERED_PLATE_IRON_STAIRS.get(),
                ModBlocks.WAXED_RUSTED_PLATE_IRON_STAIRS.get(),
                ModBlocks.CUT_IRON_STAIRS.get(),
                ModBlocks.EXPOSED_CUT_IRON_STAIRS.get(),
                ModBlocks.WEATHERED_CUT_IRON_STAIRS.get(),
                ModBlocks.RUSTED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_EXPOSED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_WEATHERED_CUT_IRON_STAIRS.get(),
                ModBlocks.WAXED_RUSTED_CUT_IRON_STAIRS.get(),
                ModBlocks.SNOWY_STONE_STAIRS.get(),
                ModBlocks.SNOWY_COBBLESTONE_STAIRS.get(),
                ModBlocks.SNOWY_STONE_BRICK_STAIRS.get(),
                ModBlocks.SANDY_STONE_STAIRS.get(),
                ModBlocks.SANDY_COBBLESTONE_STAIRS.get(),
                ModBlocks.SANDY_STONE_BRICK_STAIRS.get(),
                ModBlocks.CHARRED_STAIRS.get());
        tag(BlockTags.WALLS).add(
                ModBlocks.MOSSY_BRICK_WALL.get(),
                ModBlocks.MOSSY_STONE_WALL.get(),
                ModBlocks.STONE_WALL.get(),
                ModBlocks.CRACKED_BRICK_WALL.get(),
                ModBlocks.CRACKED_STONE_BRICK_WALL.get(),
                ModBlocks.CRACKED_NETHER_BRICK_WALL.get(),
                ModBlocks.CRACKED_DEEPSLATE_BRICK_WALL.get(),
                ModBlocks.CRACKED_DEEPSLATE_TILE_WALL.get(),
                ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_WALL.get(),
                ModBlocks.CRACKED_PRISMARINE_BRICK_WALL.get(),
                ModBlocks.CRACKED_END_STONE_BRICK_WALL.get(),
                ModBlocks.PRISMARINE_BRICK_WALL.get(),
                ModBlocks.DARK_PRISMARINE_WALL.get(),
                ModBlocks.SNOWY_STONE_WALL.get(),
                ModBlocks.SNOWY_COBBLESTONE_WALL.get(),
                ModBlocks.SNOWY_STONE_BRICK_WALL.get(),
                ModBlocks.SANDY_STONE_WALL.get(),
                ModBlocks.SANDY_COBBLESTONE_WALL.get(),
                ModBlocks.SANDY_STONE_BRICK_WALL.get());
        tag(BlockTags.WOLVES_SPAWNABLE_ON).addTag(BlockTags.DIRT);
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.CHARRED_FENCE.get());
        tag(BlockTags.WOODEN_STAIRS).add(ModBlocks.CHARRED_STAIRS.get());
        tag(BlockTags.WOODEN_SLABS).add(ModBlocks.CHARRED_SLAB.get());
    }

    protected void registerCommonTags() {

    }
}
